version: "3.7"

# For deployment on our server with traefik at forms.palcollective.com
name: forms
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - node_version=21.6.2
        - nitro_port=80
        - base_url=http://localhost
      secrets:
        - env_secrets
    environment:
      - NITRO_PORT=80
      - NITRO_HOST=0.0.0.0
      - NUXT_BASE_URL=http://localhost
      - AUTH_ORIGIN=http://localhost
      - POSTGRES_PASSWORD=postgres
    secrets:
      - env_secrets
    ports:
      - "80:80"

  db:
    restart: unless-stopped
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=headless_forms
    volumes:
      - default_database_data:/var/lib/postgresql/data

volumes:
  default_database_data:

secrets:
  env_secrets:
    file: ./.env