version: "3.7"

# For deployment on our server with traefik at forms.palcollective.com
name: forms
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - node_version=${node_version}
      secrets:
        - env_secrets
    environment:
      - NITRO_PORT=80
      - NITRO_HOST=0.0.0.0
      - BASE_URL=http://localhost
      - AUTH_ORIGIN=http://localhost
      # keep this variable congruent with those in the db container below
      - DATABASE_URL=postgres://postgres:postgres@db/headless_forms?schema=public
    secrets:
      - env_secrets
    ports:
      - "80:80"

  db:
    restart: unless-stopped
    image: postgres:latest
    # keep these variables cogruent with DATABASE_URL above
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=headless_forms
    volumes:
      - default_database_data:/var/lib/postgresql/data

volumes:
  default_database_data:

secrets:
  env_secrets:
    file: ./.env

# services:
#   app:
#     depends_on:
#       - db
#     build:
#       context: .
#       args:
#         - port=443
#     environment:
#       - DATABASE_URL=postgres://${DEFAULT_DATABASE_USER}:${DEFAULT_DATABASE_PASSWORD}@db:${DEFAULT_DATABASE_PORT}/${DEFAULT_DATABASE_DB}?schema=public
#       - AUTH_ORIGIN=https://forms.palcollective.com
#       - BASE_URL=https://forms.palcollective.com
#     env_file:
#       - /opt/openformstack/secrets/.env
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.crocodile.rule=Host(`forms.palcollective.com`)"
#       - "traefik.http.routers.crocodile.entrypoints=websecure"
#       - "traefik.http.routers.crocodile.tls.certresolver=myresolver"
#     networks:
#       - traefik
#       - database
      
#   db:
#     restart: unless-stopped
#     image: postgres:latest
#     environment:
#       - POSTGRES_DB=${DEFAULT_DATABASE_DB}
#       - POSTGRES_USER=${DEFAULT_DATABASE_USER}
#       - POSTGRES_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
#     env_file:
#       - /opt/openformstack/secrets/.env
#     volumes:
#       - /opt/openformstack/db-data:/var/lib/postgresql/data
#     ports:
#       - "$DEFAULT_DATABASE_PORT:5432"
#     networks:
#       - database

# networks:
#   database:
#     name: openformstack
#   traefik:
#     external: true